version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    command: python main.py
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=your_api_key
    tty: true  # 対話モードを有効化